---
title: "Algorithm comparison"
author: "Ana Dimitrova"
output: pdf_document

---
 

```{r setup, include=TRUE, echo=FALSE}
library(ggplot2)
library(scales)
library(gridExtra)

path = "~/Documents/ETH/Thesis/1plusX/Data/Thesis/Results/20090501_"
y_limit = 0.07

plot_results <- function(algorith_name="Random") {
  
  data <- read.csv(file=paste0(path, paste0(algorith_name, ".csv")), header=TRUE, sep=",")
  data$Percent = data$Clicks / data$Impressions
  data$Factor = paste(data$Method, data$Alpha, sep=" ")

  ggplot(data, aes(x=Impressions, y=Percent, colour=Factor)) + 
  geom_line() + xlab("Impressions") + ylab("% of Clicks") +
  expand_limits(y=c(0,0.07)) + theme_bw() + ggtitle(algo)
}
  

```

```{r random, include=TRUE, echo=FALSE}

plot_results("Random")

```

```{r e-first, include=TRUE, echo=FALSE}

plot_results("EFirst")

```

```{r e-greedy, include=TRUE, echo=FALSE}

plot_results("EGreedy")

```

```{r ucb, include=TRUE, echo=FALSE}
```

```{r linucb-disjoint, include=TRUE, echo=FALSE}
plot_results("LinUCB_Disjoint")
```

```{r linucb-hybrid, include=TRUE, echo=FALSE}
```

```{r gpprank, include=TRUE, echo=FALSE}
```
