---
title: "R Notebook"
output: html_notebook
---


```{r setup, include=TRUE, echo=FALSE}
library(ggplot2)
library(scales)
library(gridExtra)

path_mse = "~/Documents/ETH/Thesis/1plusX/Data/Thesis/1plusx/Results/MSE/"

formatterM <- function(){
  function(x) paste(x/1000000, "M")
}

formatterPretty <- function(){
  function(x) ifelse(x==10, paste(x, "% (Random)"), paste(x, "%"))
}

selectNecessaryColumns <- function(df, columns) {
  for (column in columns) {
    if(!(column %in% colnames(df))){
      df[column] = NA
    } 
  }
  df[,columns]
}

prepMSEData <- function(files) {
  data <- read.csv(file=paste0(path_mse, paste0(files[1], ".csv")), header=TRUE, sep=",")
  columns = c("MSE", "Impressions", "CumulativeMSE", "RecommendationSizePercent","TotalImpressions","Method", "Alpha","Timestamp","TrainPart")
  data = selectNecessaryColumns(data, columns)
  for (name in files){
    data1 <- read.csv(file=paste0(path_mse, paste0(name, ".csv")), header=TRUE, sep=",")
    data1 = selectNecessaryColumns(data1, columns)
    data <- rbind(data, data1)  
  }
  
  data$Factor = factor(paste(data$Method, data$Alpha, data$RecommendationSizePercent * 100))
  data$UserPercentage = factor(data$RecommendationSizePercent * 100)
  #data$Timestamp = data$Timestamp / 1000
  data$Timestamp = as.POSIXct(data$Timestamp, origin="1970-01-01")
  data
}
  
```
```{r Random_0_1, include=TRUE, echo=FALSE}

files = c("Random_0_1", "Random")
data = prepData(files)

ggplot(data, aes(x=TotalImpressions)) + 
  geom_line(aes(y=MSE, colour=Factor),linetype = "dashed") +
  geom_line(aes(y=Percent, colour=Factor)) +
    xlab("Impressions") + ylab("MSE") + 
  scale_y_continuous(sec.axis = sec_axis(~.*1, name = "CTR"))+
    theme_bw() + ggtitle("MSE Random float vs discrete")

```
```{r TS_Lin_MSE, include=TRUE, echo=FALSE}

files = c("TS_Lin_MSE", "LinUCB_Disjoint_MSE")#, "Random")
dataMSE = prepData(files)
dataCTR = prepData(files, path_ctr)
selectedMSE = dataMSE[dataMSE$TotalImpressions > 5000000,]
selectedCTR = dataCTR

g1 = ggplot(selectedMSE, aes(x=TotalImpressions)) + 
 geom_line(aes(y=MSE, colour=Factor)) +
 # stat_smooth(aes(y=MSE, colour=Factor), method = "lm", formula = y ~ poly(x, 10), se = FALSE) +
#  scale_y_log10()+
  expand_limits(y=c(0, 0.002)) +
  scale_x_continuous(labels=formatterM())+
  xlab("Impressions") + ylab("Cumulative MSE") + theme_bw() + ggtitle("Cumulative MSE") +
  theme(legend.justification=c(1,0), legend.position="bottom")  
    
g2 = ggplot(selectedCTR, aes(x=TotalImpressions)) + 
#  geom_line(aes(y=Percent, colour=Factor)) +
    stat_smooth(aes(y=Percent, colour=Factor), method = "lm", formula = y ~ poly(x, 10), se = FALSE) +
  scale_x_continuous(labels=formatterM())+
  xlab("Impressions") + ylab("CTR") + theme_bw() + ggtitle("CTR")+
  theme(legend.justification=c(1,0), legend.position="bottom")  

g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}

mylegend<-g_legend(g2)

grid.arrange(arrangeGrob(g1 + theme(legend.position="none"),
                         g2 + theme(legend.position="none"),
                               nrow=1, ncol=2, widths=unit(c(9, 9), "cm"), heights=unit(9, "cm")),
                   mylegend, nrow=2, widths=unit(18, "cm"), heights=unit(c(9, 1), "cm"))

```

```{r Random, include=TRUE, echo=FALSE}

files = c("Random")
data = prepMSEData(files)
ggplot(data, aes(x=TotalImpressions, y=CumulativeMSE, colour=Factor)) + 
  geom_line() +
#  scale_y_log10()+
    xlab("Impressions") + ylab("Cumulative MSE") +
    scale_x_continuous(labels=formatterM())+
    theme_bw() + ggtitle("Cumulative MSE LinUCB_Disjoint") +
    scale_color_discrete(name="User Percentage")

```
```{r NN, include=TRUE, echo=FALSE}

files = c("NN")
data = prepMSEData(files)
ggplot(data, aes(x=Timestamp, y=MSE, colour=Factor)) + 
  geom_line() +
#  scale_y_log10()+
    xlab("Impressions") + ylab("MSE") +
  #  scale_x_continuous(labels=formatterM())+
   theme_bw() + ggtitle("MSE NN") +
    scale_color_discrete(name="User Percentage")

```

```{r TS_Lin_Percent, include=TRUE, echo=FALSE}

files = c("TS_Lin_Percent") # , "LinUCB_Disjoint"
data = prepMSEData(files)
selected = data[data$TotalImpressions > 500000,]
ggplot(selected, aes(x=Timestamp, y=MSE, colour=Factor)) + 
  geom_line() +
#  scale_y_log10()+
    xlab("Impressions") + ylab("Cumulative MSE") +
   theme_bw() + ggtitle("MSE TS_Lin") +
    scale_color_discrete(name="User Percentage")

```
```{r TS_Lin_Train, include=TRUE, echo=FALSE}

files = c("TS_Lin_train") # , "LinUCB_Disjoint"
data = prepMSEData(files)
data$Factor = factor(paste("R:", data$RecommendationSizePercent * 100, "% T:",data$TrainPart * 100,"%", sep=""))

selected = data[data$TotalImpressions > 500000,]
ggplot(selected, aes(x=Timestamp, y=CumulativeMSE, colour=Factor)) + 
  geom_line() +
#  scale_y_log10()+
    xlab("Time") + ylab("MSE") +
   theme_bw() + ggtitle("MSE TS_Lin") +
    scale_color_discrete(name="User Percentage")

```