---
title: "R Notebook"
output: html_notebook
fig_width: 20 
---


```{r}
library(ggplot2)
library("gridExtra")
path = "~/Documents/ETH/Thesis/1plusX/Data/RawData/Campaigns/837817/Processed/sorted_time_impressions.csv"
data <- read.csv(file=path, header=TRUE, sep=",")
data$Timestamp = data$Timestamp / 1000
data$Timestamp = as.POSIXct(data$Timestamp, origin="1970-01-01")
formatterPretty <- function(){
  function(x) ifelse(x==10, paste(x, "% (Random)"), paste(x, "%"))
}

formatterK <- function(){
  function(x) ifelse(x==0, "0", paste(x/1000, "K"))
}

formatterPercent <- function(){
  function(x) paste(x*100, "%")
}


formatterTime <- function(){
  function(x) as.POSIXct( x /1000, origin="1970-01-01")
}

formatterTimeInMin <- function(){
  function(x) paste(as.integer(x/(60)))
}

formatterTimeInHour <- function(){
  function(x) paste(as.integer(x/(60*60)))
}

formatterLog <- function(){
  function(x) ifelse(log(x) < 0, 0, round(log(x), digits=1))
}
formatterDensity <- function(){
  function(x) x*10000
}

```


User Impressions per day.
```{r}
library(scales)

ggplot(data, aes(data$Timestamp, fill=Click)) + 
  geom_histogram(bins=200)+
  xlab("Time progression") + ylab("Impressions") +
  theme_bw() + ggtitle("Impressions for the duration of the campaign") +
  scale_y_continuous(labels=formatterK()) + scale_x_datetime(breaks = date_breaks("1 day"), minor_breaks = date_breaks("2 hour"))

# as.POSIXct(1529568000, origin="1970-01-01")
# as.POSIXct(1529400000, origin="1970-01-01")

```

```{r}
all_impressions = hist(data$Timestamp, breaks = "hours", 
     col="blue", main = "Histogramm of Impressions for Campaign",  
     xlab = "Timestamp", ylab = "Frequency", freq=TRUE, plot = FALSE)

click_data = data[data$Click == 1, ]
click_impressions = hist(click_data$Timestamp, breaks = "hours", 
     col="blue", main = "Histogramm of Clicks for Campaign",  
     xlab = "Timestamp", ylab = "Frequency", freq=TRUE, plot = FALSE)

all_impressions$counts[all_impressions$counts == 0] = 1 
ratio = (click_impressions$counts/all_impressions$counts) 
time = subset(click_impressions$breaks, click_impressions$breaks != 1532300400)

df = data.frame(ratio, time = time) 
df$time = as.POSIXct( time , origin="1970-01-01")
df = subset(df, df$ratio < 1)

ggplot(df, aes(x=time,y=ratio)) + 
  geom_line()+
  geom_point() +
  xlab("Time progression") + ylab("CTR") +
  theme_bw() + ggtitle("CTR for the duration of the campaign") +
  scale_y_continuous(labels=formatterPercent()) 

```

```{r}

stats_path = "~/Documents/ETH/Thesis/1plusX/Data/RawData/Campaigns/837817/Processed/user_statistics.csv"
users <- read.csv(file=stats_path, header=TRUE, sep=",")
cat(paste("Total Users", nrow(users), "\n"))
cat(paste("Total Impressions", sum(users$TotalImpressions), "\n"))
click_users = users[users$ClickCount > 0, ]
click_users$CTR = click_users$ClickCount/click_users$TotalImpressions
click_users$TimeOfFirstClick = click_users$FirstClickIndex/click_users$TotalImpressions
# 24438 unique users that clicked 
cat(paste("Number of unique users that have clicks:", nrow(click_users), "\n"))
# 285379 impressions for users that clicked 

cat(paste("Total number of impressions for the users that have clicks:", sum(click_users$TotalImpressions), "\n"))

# 143800 impressions to discard if discarding impressions past click

cat(paste("Total number of impressions that could be discarded past first clicks:", sum(click_users$TotalImpressions - click_users$FirstClickIndex), "\n"))



```

```{r}
ggplot(data=click_users, aes(CTR)) + 
  geom_histogram(bins = 50, color="blue") +
  theme_bw() + xlab("CTR") + ylab("User Count") + ggtitle("CTR for the users that have click activity.")
```

```{r, fig.height = 5, fig.width = 10}
g1 = ggplot(data=click_users, aes(ActiveTime)) + 
  geom_histogram(bins=30, color="blue") +
  theme_bw() + xlab("Time in Hours") + ylab("Density") + ggtitle("Total Active Time") + 
  scale_x_continuous(labels=formatterTimeInHour()) + expand_limits(y=c(0, 15e3))

g2 = ggplot(data=click_users, aes(TimeUntilClickSec)) + 
  geom_histogram(bins=30, color="blue") +
  theme_bw() + xlab("Time in Hours") + ylab("Density") + ggtitle("Active Time before First Click") + 
  scale_x_continuous(labels=formatterTimeInHour()) + expand_limits(y=c(0, 15e3)) 

grid.arrange(arrangeGrob(g1, g2, nrow=1, ncol=2, widths=unit(c(12, 12),"cm"), heights=unit(9, "cm")), nrow=2, widths=unit(24, "cm"), heights=unit(c(9, 1), "cm"))
```
Clearly the total active time is more evenly distributed compared to the time of the time until first click. The time until first click is almost always within 
```{r, fig.height = 5, fig.width = 10}
g1 = ggplot(data=users[users$TotalImpressions < 50,], aes(TotalImpressions)) + 
  geom_histogram(bins = 50, color="blue", aes(y=..density..)) +
  theme_bw() + xlab("# Impressions") + ylab("Density") + 
  ggtitle("Density per #Impressions for All Users (bound by 50)") +
  expand_limits(y=c(0, 0.30))+ theme(plot.title=element_text(size=12))
  
g2 = ggplot(data=click_users[click_users$TotalImpressions < 50,], aes(TotalImpressions)) + 
  geom_histogram(bins = 50, color="blue", aes(y=..density..)) +
  theme_bw() + xlab("# Impressions") + ylab("Density") + ggtitle("Density for #Impressions for Click Users (bound by 50)") +
  expand_limits(y=c(0, 0.30)) + theme(plot.title=element_text(size=12))
  

grid.arrange(arrangeGrob(g1, g2, nrow=1, ncol=2, widths=unit(c(12, 12),"cm"), heights=unit(9, "cm")), nrow=2, widths=unit(24, "cm"), heights=unit(c(9, 1), "cm"))
```

```{r, fig.height = 5, fig.width = 10}

g1 = ggplot(data=click_users, aes(TotalImpressions)) + 
  geom_histogram(bins = 50, color="blue", aes(y=..density..)) +
  theme_bw() + xlab("# Total Impressions") + ylab("Density") + ggtitle("Density for #Impressions (Click Users)") +
  expand_limits(y=c(0, 0.25)) + theme(plot.title=element_text(size=12))
  
g2 = ggplot(data=click_users, aes(FirstClickIndex)) + 
  geom_histogram(bins = 50, color="blue", aes(y=..density..)) +
  theme_bw() + xlab("First Click Index") + ylab("Density") + ggtitle("Density for First Click Index (Click Users)") +
  expand_limits(y=c(0, 0.25)) + theme(plot.title=element_text(size=12))

grid.arrange(arrangeGrob(g1, g2, nrow=1, ncol=2, widths=unit(c(12, 12),"cm"), heights=unit(9, "cm")), nrow=2, widths=unit(24, "cm"), heights=unit(c(9, 1), "cm"))
```

