---
title: "Algorithm comparison"
author: "Ana Dimitrova"
output: pdf_document

---
 

```{r setup, include=TRUE, echo=FALSE}
library(ggplot2)
library(scales)
library(gridExtra)

path = "~/Documents/ETH/Thesis/1plusX/Data/Thesis/1plusx/Results/"
path_ctr = "~/Documents/ETH/Thesis/1plusX/Data/Thesis/1plusx/Results/CTR/"
plot_results <- function(algorith_name="Random") {
  
  data <- read.csv(file=paste0(path, paste0(algorith_name, ".csv")), header=TRUE, sep=",")
  data$Percent = data$Clicks / data$Impressions * 100
  data$Factor = paste(data$Method, sep=" ")

  ggplot(data, aes(x=TotalImpressions, y=Percent, colour=Factor)) + 
    stat_smooth(aes(x = TotalImpressions, y = Percent), method = "lm",
                formula = y ~ poly(x, 10), se = FALSE) +
    xlab("Impressions") + ylab("% of Clicks") +
    #expand_limits(y=c(4,7.5), x=c(0, 225000)) + 
    theme_bw() + ggtitle(algorith_name)
}

formatterM <- function(){
  function(x) paste(x/1000000, "M")
}

formatterPretty <- function(){
  function(x) ifelse(x==10, paste(x, "% (Random)"), paste(x, "%"))
}

selectNecessaryColumns <- function(df, columns) {
  for (column in columns) {
    if(!(column %in% colnames(df))){
      df[column] = NA
    } 
  }
  df[,columns]
}

prepData <- function(files, path="~/Documents/ETH/Thesis/1plusX/Data/Thesis/1plusx/Results/") {
  data <- read.csv(file=paste0(path, paste0(files[1], ".csv")), header=TRUE, sep=",")
  columns = c("Clicks", "Impressions", "RecommendationSizePercent","TotalImpressions","Method", "Alpha","Timestamp","TrainPart", "MSE", "CumulativeMSE")
  data = selectNecessaryColumns(data, columns)
  for (name in files){
    data1 <- read.csv(file=paste0(path, paste0(name, ".csv")), header=TRUE, sep=",")
    data1 = selectNecessaryColumns(data1, columns)
    data <- rbind(data, data1)  
  }
  data$Percent = data$Clicks / data$Impressions * 100
  data$Factor = factor(paste(data$Method, " ", data$Alpha, " R:", data$RecommendationSizePercent * 100, sep=""))
  data$UserPercentage = factor(data$RecommendationSizePercent * 100)
  #data$Timestamp = data$Timestamp / 1000
  data$Timestamp = as.POSIXct(data$Timestamp, origin="1970-01-01")
  data
}
  
```

```{r best, include=TRUE, echo=FALSE}

files =  c("LinUCB_Disjoint", "TS_Lin", "Regression", "Random")
data = prepData(files)
data$Factor = factor(paste(data$Method, data$RecommendationSizePercent, data$Alpha* 100))


               

ggplot(data, aes(x=TotalImpressions, y=Percent, colour=Factor)) + 
  geom_line() +
    xlab("Impressions") + ylab("% of Clicks") +
    expand_limits(y=c(0,1.2)) + 
 #   scale_x_continuous(labels=formatterM()) + 
  theme_bw() + ggtitle("LinUCB_Disjoint (Cumulative)") +
    scale_color_discrete(name="Algo Details/Alpha", labels=formatterPretty())
```

```{r Regression, include=TRUE, echo=FALSE}

files = c("Random", "Regression")
data = prepData(files)

data$Factor = factor(paste(data$Method," R:", data$RecommendationSizePercent * 100, sep=""))

ggplot(data, aes(x=TotalImpressions, y=Percent, colour=Factor)) + 
    geom_line() +
    xlab("Impressions") + ylab("% of Clicks") +
    expand_limits(y=c(0,1.25)) + 
    scale_x_continuous(labels=formatterM())+
    theme_bw() + ggtitle("Regression (Cumulative)") +
    scale_color_discrete(name="Method")
```

```{r Regression, include=TRUE, echo=FALSE}

files =  c("Regression", "Random")
data = prepData(files)
data$Factor = factor(paste(data$Method, data$RecommendationSizePercent, data$Alpha* 100))

ggplot(data, aes(x=TotalImpressions, y=Percent, colour=Factor)) + 
  geom_line() +
    xlab("Impressions") + ylab("% of Clicks") +
    expand_limits(y=c(0,1.2)) + 
 #   scale_x_continuous(labels=formatterM()) + 
  theme_bw() + ggtitle("Regression") +
    scale_color_discrete(name="Algo Details/Alpha", labels=formatterPretty())
```

```{r all_algos, include=TRUE, echo=FALSE}

files = c("Regression_clustered")
data = prepData(files)

data$Factor = factor(paste(data$Method," R:", data$RecommendationSizePercent * 100, sep=""))

ggplot(data, aes(x=TotalImpressions, y=Percent, colour=Factor)) + 
  geom_line() +  
  #stat_smooth(aes(x=TotalImpressions, y=Percent), method = "lm", formula = y ~ poly(x, 21), se = FALSE) +
    xlab("Impressions") + ylab("% of Clicks") +
    expand_limits(y=c(0,1.2)) + 
    #scale_x_continuous(labels=formatterM())+
    theme_bw() + ggtitle("Regression_clustered  (Cumulative)") +
    scale_color_discrete(name="User Percentage")
```

```{r LinUCB_Disjoint, include=TRUE, echo=FALSE}

files = c("LinUCB_Disjoint")
data = prepData(files)

data$Factor = factor(paste(data$Method, data$RecommendationSizePercent, data$Alpha* 100))
#data = data[ data$Alpha == 0.02,]
ggplot(data, aes(x=TotalImpressions, y=Percent, colour=Factor)) + 
  geom_line() +
    xlab("Impressions") + ylab("% of Clicks") +
    expand_limits(y=c(0,1.2)) + 
 #   scale_x_continuous(labels=formatterM()) + 
  theme_bw() + ggtitle("LinUCB_Disjoint (Cumulative)") +
    scale_color_discrete(name="Algo Details/Alpha", labels=formatterPretty())
```

```{r TS_Lin, include=TRUE, echo=FALSE}

files = c("TS_Lin")
data = prepData(files)

ggplot(data, aes(x=TotalImpressions, y=Percent, colour=Factor)) + 
  geom_line() +
    xlab("Impressions") + ylab("% of Clicks") +
    expand_limits(y=c(0,1.2)) + 
    scale_x_continuous(labels=formatterM())+
    theme_bw() + ggtitle("TS_Lin (Cumulative)") +
    scale_color_discrete(name="TS_Lin", labels=formatterPretty())
```

```{r LinUCB_Disjoint_Non_Cumulative, include=TRUE, echo=FALSE}
files = c("LinUCB_Disjoint", "TS_Lin","TS_Lin_Equalize")
data = prepData(files, path_ctr)
    
data$Percent = data$Clicks / data$Impressions * 100
data$Factor = factor(paste(data$Method, data$Alpha, data$RecommendationSizePercent * 100))
data$UserPercentage = factor(data$RecommendationSizePercent * 100)
data = data[(
            (data$Alpha == 0.01 & data$Method != "TS_Lin" ) | 
              data$Method == "Random" | 
              data$Method == "TS_Lin_GRS"|
              (data$Method == "TS_Lin" & data$RecommendationSizePercent == 0.02 & data$Alpha == 0.0001)) ,]
data$Factor = factor(paste(data$Method, data$Alpha*100))
ggplot(data, aes(x=TotalImpressions, y=Percent, colour=Factor)) + 
  #geom_line() + 
  stat_smooth(aes(x=TotalImpressions, y=Percent), method = "lm",formula = y ~ poly(x, 20), se = FALSE) +
    xlab("Impressions") + ylab("% of Clicks") +
    expand_limits(y=c(0,1.5)) + 
   scale_x_continuous(labels=formatterM()) + 
  theme_bw() + ggtitle("LinUCB_Disjoint (NonClumulative)") +
    scale_color_discrete(name="Algo Details/Alpha", labels=formatterPretty())
```
```{r LinUCB_Disjoint_Non_Cumulative, include=TRUE, echo=FALSE}

files = c("LinUCB_Disjoint", "TS_Lin")
data = prepData(files, path_ctr)
    
data$Percent = data$Clicks / data$Impressions * 100
data$Factor = factor(paste(data$Method, data$Alpha, data$RecommendationSizePercent * 100))
data$UserPercentage = factor(data$RecommendationSizePercent * 100)
data = data[data$Method != "LinUCB_Disjoint_EW" & (
            (data$Alpha == 0.01 & data$Method != "TS_Lin" ) | 
              data$Method == "Random" | 
              (data$Method == "TS_Lin" & data$RecommendationSizePercent == 0.02 & data$Alpha == 0.0001)) ,]
data$Factor = factor(paste(data$Method, data$Alpha*100))
ggplot(data, aes(x=Timestamp, y=Percent, colour=Factor)) + 
  #geom_line() + 
  stat_smooth(aes(x=Timestamp, y=Percent), method = "lm",formula = y ~ poly(x, 20), se = FALSE) +
    xlab("Timeline") + ylab("% of Clicks") +
    expand_limits(y=c(0,1.5)) + 
   # scale_x_continuous(labels=formatterM()) + 
  theme_bw() + ggtitle("LinUCB_Disjoint (NonClumulative)") +
    scale_color_discrete(name="Algo Details/Alpha", labels=formatterPretty())
```

```{r TS_Lin, include=TRUE, echo=FALSE}

files = c("TS_Lin")
data = prepData(files)

ggplot(data, aes(x=TotalImpressions, y=Percent, colour=Factor)) + 
  geom_line() +
    xlab("Impressions") + ylab("% of Clicks") +
    expand_limits(y=c(0,1.2)) + 
    scale_x_continuous(labels=formatterM())+
    theme_bw() + ggtitle("TS_Lin (Cumulative)") +
    scale_color_discrete(name="TS_Lin", labels=formatterPretty())
```

```{r NN, include=TRUE, echo=FALSE}

files = c("NN")
data = prepData(files)

ggplot(data, aes(x=TotalImpressions, y=Percent, colour=Factor)) + 
  geom_line() +
    #stat_smooth(aes(x=Timestamp, y=Percent), method = "lm",formula = y ~ poly(x, 21), se = FALSE) +
    xlab("Impressions") + ylab("CTR") +
    expand_limits(y=c(0,0.5)) + 
    scale_x_continuous(labels=formatterM())+
    theme_bw() + ggtitle("NN CTR (Cumulative)") +
    scale_color_discrete(name="NN", labels=formatterPretty())
```

```{r TS_Lin_Train, include=TRUE, echo=FALSE}

files = c("TS_Lin_train", "TS_Lin_Equalize")
data = prepData(files)
data = data[data$RecommendationSizePercent == 0.02 & data$TrainPart == 0.02,]
data$Factor = factor(paste(data$Method, " R:", data$RecommendationSizePercent * 100, "% T:",data$TrainPart * 100,"%", sep=""))
ggplot(data, aes(x=Timestamp, y=Percent, colour=Factor)) + 
  geom_line() +
    xlab("Impressions") + ylab("% of Clicks") +
    expand_limits(y=c(0,1.2)) + 
  #  scale_x_continuous(labels=formatterM())+
    theme_bw() + ggtitle("TS_Lin (Cumulative)") +
    scale_color_discrete(name="TS_Lin")
```


Non-cumulative comparison between gradual recommendation size change vs a direct change to target recommendation size. Difference is minor.
```{r LinUCB_Disjoint_Non_Cumulative, include=TRUE, echo=FALSE}
files = c("TS_Lin","TS_Lin_Equalize")
data = prepData(files, path_ctr)
    
data$Percent = data$Clicks / data$Impressions * 100

data = data [data$Method == "TS_Lin_GRS" | (data$Method == "TS_Lin" & data$Alpha == 0.0001),]
data$Factor = factor(paste(data$Method, data$Alpha*100))
ggplot(data, aes(x=Timestamp, y=Percent, colour=Factor)) + 
  #geom_line() + 
  stat_smooth(aes(x=Timestamp, y=Percent), method = "lm",formula = y ~ poly(x, 20), se = FALSE) +
    xlab("Timeline") + ylab("% of Clicks") +
    expand_limits(y=c(0,1.5)) + 
   # scale_x_continuous(labels=formatterM()) + 
  theme_bw() + ggtitle("LinUCB_Disjoint (NonClumulative)") +
    scale_color_discrete(name="Algo Details/Alpha", labels=formatterPretty())
```

```{r GP_Clustered_10, include=TRUE, echo=FALSE}

files = c("GP_Clustered_10")
data = prepData(files)
#data = data[data$Alpha == 0.0001, ]
data$Factor = factor(paste("R:",data$RecommendationSizePercent * 100, "% A:", data$Alpha*100, sep=""))
ggplot(data, aes(x=TotalImpressions, y=Percent, colour=Factor)) + 
  geom_line() +
    xlab("Impressions") + ylab("% of Clicks") +
    expand_limits(y=c(0,0.3)) + 
    scale_x_continuous(labels=formatterM())+
    theme_bw() + ggtitle("GP_Clustered_10 (Cumulative)") +
    scale_color_discrete(name="GP_Clustered_10", labels=formatterPretty())
```

```{r best, include=TRUE, echo=FALSE}

files = c("LinUCB_Disjoint", "LinUCB_Disjoint_Test", "Random", "GP_Clustered_Test", "TS_Lin_Test")
data = prepData(files)

data = data[(data$Method == "LinUCB_Disjoint" & data$RecommendationSizePercent == 0.02 & data$Alpha == 0.02) |
            (data$Method == "LinUCB_Disjoint_Test_E_0.8")|
            (data$Method == "Random") | 
              (data$Method == "GP_Clustered_Test" )|
              (data$Method == "TS_Lin_Test_E_0.8" )
            ,]

ggplot(data, aes(x=Timestamp, y=Impressions, colour=Factor)) + 
  geom_line() +
   expand_limits(y=c(0,1000000)) + 
   #scale_x_continuous(labels=formatterM())+
  scale_y_continuous(labels=formatterM())+
    theme_bw() + ggtitle("All (Cumulative)") +
    scale_color_discrete(name="User Percentage")
```