---
title: "Algorithm comparison"
author: "Ana Dimitrova"
output: pdf_document

---
 

```{r setup, include=TRUE, echo=FALSE}
library(ggplot2)
library(scales)
library(gridExtra)

path = "~/Documents/ETH/Thesis/1plusX/Data/Thesis/Results/"
plot_results <- function(algorith_name="Random") {
  
  data <- read.csv(file=paste0(path, paste0(algorith_name, ".csv")), header=TRUE, sep=",")
  data$Percent = data$Clicks / data$Impressions * 100
  data$Factor = paste(data$Method, data$Alpha, sep=" ")

  ggplot(data, aes(x=Impressions, y=Percent, colour=Factor)) + 
  geom_line() + xlab("Impressions") + ylab("% of Clicks") +
  expand_limits(y=c(4,7.5), x=c(0, 225000)) + theme_bw() + ggtitle(algorith_name)
}
  
```

```{r all_algos, include=TRUE, echo=FALSE}

data <- read.csv(file=paste0(path, paste0("LinUCB_Disjoint", ".csv")), header=TRUE, sep=",")
data1 <- read.csv(file=paste0(path, paste0("LinUCB_Hybrid", ".csv")), header=TRUE, sep=",")
data <- rbind(data, data1)
data1 <- read.csv(file=paste0(path, paste0("Random", ".csv")), header=TRUE, sep=",")
data <- rbind(data, data1)
data1 <- read.csv(file=paste0(path, paste0("EFirst", ".csv")), header=TRUE, sep=",")
data <- rbind(data, data1)
data1 <- read.csv(file=paste0(path, paste0("EGreedy", ".csv")), header=TRUE, sep=",")
data <- rbind(data, data1)
data1 <- read.csv(file=paste0(path, paste0("EGreedy_Lin", ".csv")), header=TRUE, sep=",")
data <- rbind(data, data1)
#data1 <- read.csv(file=paste0(path, paste0("EGreedy_Seg_Lin", ".csv")), header=TRUE, sep=",")
#data <- rbind(data, data1)
data1 <- read.csv(file=paste0(path, paste0("EGreedy_Hybrid", ".csv")), header=TRUE, sep=",")
data <- rbind(data, data1)
data1 <- read.csv(file=paste0(path, paste0("EGreedy_Disjoint", ".csv")), header=TRUE, sep=",")
data <- rbind(data, data1)
data1 <- read.csv(file=paste0(path, paste0("EGreedy_Seg", ".csv")), header=TRUE, sep=",")
data <- rbind(data, data1)
data1 <- read.csv(file=paste0(path, paste0("UCB", ".csv")), header=TRUE, sep=",")
data <- rbind(data, data1)
data1 <- read.csv(file=paste0(path, paste0("UCB_Seg", ".csv")), header=TRUE, sep=",")
data <- rbind(data, data1)

data$Percent = data$Clicks / data$Impressions * 100
data$Factor = paste(data$Method, data$Alpha, sep=" ")

selected = data[(data$Method == "Random") 
      | (data$Method == "EFirst" && data$Alpha == 0.1) 
      | (data$Method == "EGreedy" & data$Alpha == 0.1)
      | (data$Method == "EGreedy_Lin" & data$Alpha == 0.05)
      | (data$Method == "EGreedy_Seg" & data$Alpha == 0.1) 
      | (data$Method == "EGreedy_Seg_Lin" & data$Alpha == 0.0) 
      | (data$Method == "EGreedy_Disjoint" & data$Alpha == 0.1) 
      | (data$Method == "EGreedy_Hybrid" & data$Alpha == 0.1) 
      | (data$Method == "UCB" & data$Alpha == 0.05) 
      | (data$Method == "UCB_Seg" & data$Alpha == 0.05) 
      | (data$Method == "LinUCB_Disjoint" & data$Alpha == 0.2) 
      | (data$Method == "LinUCB_Hybrid" & data$Alpha == 0.2), ]

ggplot(selected, aes(x=Impressions, y=Percent, colour=Factor)) + 
  geom_line() + xlab("Impressions") + ylab("% of Clicks") +
  expand_limits(y=c(4,7.5), x=c(0, 225000)) + theme_bw() + 
  ggtitle("All algorithms with best parameters")

```

```{r random, include=TRUE, echo=FALSE}

plot_results("Random")

```

```{r e-first, include=TRUE, echo=FALSE}

plot_results("EFirst")

```

```{r e-greedy, include=TRUE, echo=FALSE}

plot_results("EGreedy")

```

```{r e-greedy_Seg, include=TRUE, echo=FALSE}

plot_results("EGreedy_Lin")

```

```{r e-greedy_Seg, include=TRUE, echo=FALSE}

plot_results("EGreedy_Seg_Lin")

```

```{r e-greedy_Seg, include=TRUE, echo=FALSE}

plot_results("EGreedy_Seg")

```
```{r egreedy-disjoint, include=TRUE, echo=FALSE}
plot_results("EGreedy_Disjoint")
```

```{r egreedy-hybrid, include=TRUE, echo=FALSE}
plot_results("EGreedy_Hybrid")
```

```{r ucb, include=TRUE, echo=FALSE}

plot_results("UCB")
```

```{r ucb_seg, include=TRUE, echo=FALSE}

plot_results("UCB_Seg")
```

```{r linucb-disjoint, include=TRUE, echo=FALSE}
plot_results("LinUCB_Disjoint")
```

```{r linucb-hybrid, include=TRUE, echo=FALSE}
plot_results("LinUCB_Hybrid")
```

```{r all_algos, include=TRUE, echo=FALSE}

data <- read.csv(file=paste0(path, paste0("EGreedy_Lin", ".csv")), header=TRUE, sep=",")
data1 <- read.csv(file=paste0(path, paste0("EGreedy_Lin_Hybrid_1", ".csv")), header=TRUE, sep=",")

data <- rbind(data, data1)

data$Percent = data$Clicks / data$Impressions * 100
data$Factor = paste(data$Method, data$Alpha, sep=" ")

selected = data[(data$Method == "EGreedy_Lin" & data$Alpha == 0.01)
      | (data$Method == "EGreedy_Lin_Hybrid_1" ), ]

ggplot(selected, aes(x=Impressions, y=Percent, colour=Factor)) + 
  geom_line() + xlab("Impressions") + ylab("% of Clicks") +
  expand_limits(y=c(4,7.5), x=c(0, 225000)) + theme_bw() + 
  ggtitle("All algorithms with best parameters")
```
